# Generated by Django 4.2 on 2026-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Optional unique ISBN identifier (ISBN-10 or ISBN-13)', max_length=20, null=True, unique=True),
        ),
    ]
