# Generated by Django 4.2 on 2026-08-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('cancel', 'Cancel')], default='adjustment', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='books.book')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
