# Generated by Django 4.2 on 2026-08-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='books.book'),
        ),
    ]
