# Generated by Django 4.2 on 2026-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
