# Generated by Django 4.2 on 2026-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_fulfilled_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Ready_For_Delivery', 'Ready for Delivery'), ('Ready_For_Pickup', 'Ready for Pickup'), ('Delivered', 'Delivered'), ('Picked_Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
