# Generated by Django 4.2 on 2026-08-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_order_delivery_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_type',
            field=models.CharField(choices=[('order', 'Order'), ('walk_in', 'Walk-in')], default='order', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Required for formal orders; optional for walk-in sales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Ready_For_Delivery', 'Ready for Delivery'), ('Ready_For_Pickup', 'Ready for Pickup'), ('Delivered', 'Delivered'), ('Picked_Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
